# Generated by Django 4.1.3 on 2022-12-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_option_answer_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["text"],
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="questionare",
            options={
                "ordering": ["name"],
                "verbose_name": "набор тестов",
                "verbose_name_plural": "наборы тестов",
            },
        ),
        migrations.AlterField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
                verbose_name="вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="questionare",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="owner",
                to="quiz.question",
                verbose_name="вопросы",
            ),
        ),
    ]
